chore(build): prerelease wip

diff --git a/src/bin/cluster b/src/bin/cluster
--- a/src/bin/cluster
+++ b/src/bin/cluster
@@ -11,16 +11,24 @@
 # License:      MIT License
 # Copyright:    Copyright © 2023 Darren (Ragdata) Poulton
 # ==================================================================
+# DESCRIPTION
+# ==================================================================
+# The 'cluster' command allows you to create and store records which
+# contain the details of each node in your cluster, and give you the
+# ability to configure each node remotely via ssh / scp
+# ==================================================================
 # PREFLIGHT
 # ==================================================================
 # set debug mode = false
 if [[ -z "$DEBUG" ]]; then export DEBUG=0; fi
 # if script is called with 'debug' as an argument, then set debug mode
 if [[ "${1:l}" == "debug" ]] || [[ "$DEBUG" == 1 ]]; then shift; DEBUG=1; set -- "${@}"; set -axeET; else set -aeET; fi
+# create logFile if not already specified
+if [[ -z "$logFile" ]]; then logFile=CLUSTER-"$(logTime)"; log::init "$logFile"; fi
 # ==================================================================
 # DEPENDENCIES
 # ==================================================================
-
+if ! grep -q 'function' <<< "$(type loadSource 2> /dev/null)"; then source /usr/local/lib/common.zsh; fi
 # ==================================================================
 # VARIABLES
 # ==================================================================
@@ -34,12 +42,39 @@ export CLUSTER_BUILD_DATE="20230718-0033"
 # FUNCTIONS
 # ==================================================================
 # ------------------------------------------------------------------
-# cluster::addNode
+# cluster::node::add
 # ------------------------------------------------------------------
 cluster::node::add()
 {
-	# GLOBAL VARS
+	local cluster
+
+	cluster="$(cluster::getName)"
+
+	if [[ -z "$cluster" ]]; then log::exit "cluster::node::add :: Cluster Not Found!"; fi
+
 	DIALOG_BACKTITLE="CLUSTER MANAGER"
+
+	local RESULT NODE_IP DEFAULT
+
+	DEFAULT=$(hashGET "${cluster:u}" NODE_IP)
+
+	# NODE IP
+	DIALOG_TITLE="Node IP"
+	DIALOG_TEXT="Enter Node IP:"
+	DIALOG_INIT="${NODE_IP:-"${DEFAULT}"}"
+	RESULT=$(dialog --ok-label "${OK_LABEL:-OK}" \
+		--cancel-label "${CANCEL_LABEL:-Cancel}" \
+		--backtitle "${DIALOG_BACKTITLE}" \
+		--title "${DIALOG_TITLE}" --cr-wrap --clear \
+		--inputbox "\n${DIALOG_TEXT}\n" "${HEIGHT:-15}" "${WIDTH:-50}" "${DIALOG_INIT}" 3>&1 1>&2 2>&3)
+	status=$?
+	case "$status" in
+		0)
+			[[ -z "$RESULT" ]] && log::exit "No Result Returned for NODE_IP"
+			NODE_IP="$RESULT"
+			hashSET "${cluster:u}" NODE_IP "$NODE_IP"
+			;;
+	esac
 
 	local RESULT NODE_HOSTNAME
 
@@ -55,29 +90,9 @@ cluster::node::add()
 	status=$?
 	case "$status" in
 		0)
-			[[ -z "$RESULT" ]] && errorReturn "No Result Returned"
+			[[ -z "$RESULT" ]] && log::exit "No Result Returned NODE_HOSTNAME"
 			NODE_HOSTNAME="$RESULT"
-			hashSET "${NODE_HOSTNAME:u}" NODE_HOSTNAME "$NODE_HOSTNAME"
-			;;
-	esac
-
-	local RESULT NODE_IP
-
-	# NODE IP
-	DIALOG_TITLE="Node IP"
-	DIALOG_TEXT="Enter Node IP:"
-	DIALOG_INIT="${NODE_IP:-}"
-	RESULT=$(dialog --ok-label "${OK_LABEL:-OK}" \
-		--cancel-label "${CANCEL_LABEL:-Cancel}" \
-		--backtitle "${DIALOG_BACKTITLE}" \
-		--title "${DIALOG_TITLE}" --cr-wrap --clear \
-		--inputbox "\n${DIALOG_TEXT}\n" "${HEIGHT:-15}" "${WIDTH:-50}" "${DIALOG_INIT}" 3>&1 1>&2 2>&3)
-	status=$?
-	case "$status" in
-		0)
-			[[ -z "$RESULT" ]] && errorReturn "No Result Returned"
-			NODE_IP="$RESULT"
-			hashSET "${NODE_HOSTNAME:u}" NODE_IP "$NODE_IP"
+			hashSET "${cluster:u}" NODE_HOSTNAME "$NODE_HOSTNAME"
 			;;
 	esac
 
@@ -95,11 +110,13 @@ cluster::node::add()
 	status=$?
 	case "$status" in
 		0)
-			[[ -z "$RESULT" ]] && errorReturn "No Result Returned"
+			[[ -z "$RESULT" ]] && log::exit "No Result Returned for NODE_USER"
 			NODE_USER="$RESULT"
-			hashSET "${NODE_HOSTNAME:u}" NODE_USER "$NODE_USER"
+			hashSET "${cluster:u}" NODE_USER "$NODE_USER"
 			;;
 	esac
+
+	local RESULT NODE_PASSWORD
 
 	# NODE USER PASSWORD
 	DIALOG_TITLE="Node User Password"
@@ -113,9 +130,9 @@ cluster::node::add()
 	status=$?
 	case "$status" in
 		0)
-			[[ -z "$RESULT" ]] && errorReturn "No Result Returned"
+			[[ -z "$RESULT" ]] && log::exit "No Result Returned NODE_PASSWORD"
 			NODE_PASSWORD="$RESULT"
-			hashSET "${NODE_HOSTNAME:u}" NODE_PASSWORD "$NODE_PASSWORD"
+			hashSET "${cluster:u}" NODE_PASSWORD "$NODE_PASSWORD"
 			;;
 	esac
 
@@ -141,7 +158,7 @@ cluster::node::add()
 	case "$status" in
 		0)
 			NODE_TYPE="$RESULT"
-			hashSET "${NODE_HOSTNAME:u}" NODE_TYPE "$NODE_TYPE"
+			hashSET "${cluster:u}" NODE_TYPE "$NODE_TYPE"
 			;;
 	esac
 
@@ -168,8 +185,22 @@ cluster::node::add()
 			esac
 			;;
 	esac
-
 }
+# ------------------------------------------------------------------
+# cluster::create
+# ------------------------------------------------------------------
+cluster::create()
+{
+	local name="${1:-}"
+
+	if [[ -z "$name" ]]; then log::exit "cluster::create :: Missing Argument!"; fi
+
+	stringSET CLUSTER_NAME "$1"
+}
+# ------------------------------------------------------------------
+# cluster::getName
+# ------------------------------------------------------------------
+cluster::getName() { stringGET CLUSTER_NAME; }
 # ------------------------------------------------------------------
 # cluster::node::createKey
 # ------------------------------------------------------------------
@@ -183,6 +214,44 @@ cluster::node::createKey()
 cluster::node::selectKey()
 {
 	clear
+}
+# ------------------------------------------------------------------
+# cluster::node::push
+# ------------------------------------------------------------------
+cluster::node::push()
+{
+	local
+}
+# ------------------------------------------------------------------
+# cluster::node::remove
+# ------------------------------------------------------------------
+cluster::node::remove()
+{
+	local
+}
+# ------------------------------------------------------------------
+# cluster::node::update
+# ------------------------------------------------------------------
+cluster::node::update()
+{
+	local
+}
+# ------------------------------------------------------------------
+# cluster::help
+# ------------------------------------------------------------------
+cluster::help()
+{
+	echo
+	echo "${GOLD}====================================================================${RESET}"
+	echo "${WHITE}'CLUSTER' COMMAND HELP${RESET}"
+	echo "${GOLD}====================================================================${RESET}"
+	echo
+
+
+
+	echo
+	echo "${GOLD}====================================================================${RESET}"
+	echo
 }
 # ------------------------------------------------------------------
 # cluster::version
@@ -214,24 +283,39 @@ cluster::version()
 # ==================================================================
 # trap 'errorHandler "LINENO" "BASH_LINENO" "${BASH_COMMAND}" "${?}"' ERR
 
-checkShell
-checkRoot
-
 opt="${1:l}"
 
-[[ -z "$1" ]] && opt=install
+[[ -z "$1" ]] && opt=help
 
 case "$opt" in
+	create)
+		cluster::create "$2"
+		;;
 	node)
 		case "$2" in
 			add)
 				cluster::node::add
+				;;
+			config)
+				cluster::node::config
+				;;
+			push)
+				cluster::node::push
+				;;
+			rm|remove)
+				cluster::node::remove
+				;;
+			update)
+				cluster::node::update
 				;;
 			*)
 				echo "Invalid Option 'node $2'"
 				exit 1
 				;;
 		esac
+		;;
+	help)
+		cluster::help
 		;;
 	ver|version)
 		if [[ "$#" -lt 2 ]]; then
